name: Scheduled GET Request

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 5 minutes
         # Optional: allow manual trigger

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Hit GET Request URL
        run: |
          RESPONSE=$(curl -s https://student-result-management-system-bvv6.onrender.com/api/result-formats)
          echo "Response: $RESPONSE"
          RESPONSE2=$(curl -s https://hospital-food-delivery-management-system-7gop.onrender.com/api/admin/meal-tasks-all)
          echo "Response: $RESPONSE2"
