name: Scheduled GET Request

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 5 minutes
       # Optional: allow manual trigger

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Hit GET Request URL
        run: |
          RESPONSE=$(curl -s https://student-result-management-system-bvv6.onrender.com/api/result-formats)
          echo "Response: $RESPONSE"
